# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Compile the Project
      run: mvn compile

    - name: Compile the Project
      run: mvn test

    # Step 2: Install OWASP Dependency-Check
    - name: Install OWASP Dependency-Check
      run: |
          wget https://github.com/jeremydmiller/cake-dependency-check/releases/download/v6.3.1/dependency-check-6.3.1-release.zip
          unzip dependency-check-6.3.1-release.zip
          mv dependency-check-6.3.1 /opt/dependency-check
          chmod +x /opt/dependency-check/bin/dependency-check.sh

      # Step 3: Run Dependency-Check
    - name: Run OWASP Dependency-Check
      run: |
          /opt/dependency-check/bin/dependency-check.sh --project ${{ github.repository }} --scan . --out . --format HTML
          
      # Step 4: Upload Dependency-Check Report as Artifact
    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v3
      with:
          name: dependency-check-report
          path: dependency-check-report.html

    - name: Build with Maven
      run: mvn package --file pom.xml

    
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
